# Generated by Django 3.1.5 on 2021-01-27 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=255)),
                ('matn', models.TextField()),
                ('elon_vaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqti', models.DateTimeField(auto_now=True)),
                ('link_matn', models.SlugField(max_length=255, unique_for_date='elon_vaqti')),
                ('holati', models.CharField(choices=[('qoralama', 'Qoralama'), ('chop etilgan', 'Chop etilgan')], default='qoralama', max_length=255)),
                ('korildi', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=255)),
                ('toifa', models.CharField(choices=[('ichki', 'mahalliy'), ('tashqi', 'xorijiy')], max_length=255)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xabarlar',
                'ordering': ['-yaratilgan_vaqti'],
            },
        ),
    ]
